name: EACL2021
tagline: The 16th Conference of the European Chapter <br/> of the Association for Computational Linguistics
date: April 19 &ndash; 23 <br> 2021
proceedings_title: Proceedings of the 2021 Conference on Empirical Methods in Natural Language Processing
citation_date: April 2021
analytics: UA-179777566-1
site_url: https://virtual2021.eacl.org
logo:
  image: static/images/eacl2021/acl-logo.png
  height: 45px
site_title: EACL2021
page_title:
  prefix: 'EACL2021'
  separator: ': '
background_image: static/images/eacl2021/eacl-2021-main.png
organization: Association for Computational Linguistics

# Path to the folder of paper images.
paper_images_path: https://emnlp2020-public.s3.amazonaws.com/paper_images

default_presentation_id: 38931484

# Remove or change to your chat server.
chat_server: emnlp2020.rocket.chat
channels_stats_server: https://emnlp2020-channels-stats.azure-api.net

gather_town: https://www.virtualchair.net/events/emnlp2020
connected_papers_conference_name: EMNLP2020

calendar:
  start: '2021-04-19'
  end: '2021-04-23'
